Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -28,12 +28,10 @@ jobs:
       run: |
         # Ensure the file exists before attempting to copy it
         if [ -f hello.txt ]; then
-          scp -o StrictHostKeyChecking=no hello.txt user@192.168.1.7:/home/mega/uploads/
+          scp -o StrictHostKeyChecking=no hello.txt mega@122.165.254.175:/home/mega/uploads/
         else
-          echo "hello.txt not found!"
-          exit 1
-        fi
-
+          echo "hello.txt not found!"          exit 1
+       fi
     - name: SSH to server and navigate to directory
       run: |
-        ssh -o StrictHostKeyChecking=no user@192.168.1.7 "cd /home/mega/uploads/ && ls -l"
+        ssh -o StrictHostKeyChecking=no mega@122.165.254.175 "cd /home/mega/uploads/ && ls -l"
